import{a as P,S,i}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="53514821-85afacbf4adfab5c71570a964",q="https://pixabay.com/api/",B=15;async function f(t,r){try{const a={key:v,q:t,page:r,per_page:B,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await P.get(q,{params:a})).data}catch{console.error("API error")}}const u=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".loadMore"),$=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:300});function h(t){const r=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:n,comments:w,downloads:E})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${n}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${E}</p>
        </div>
      </li>
    `).join("");u.insertAdjacentHTML("beforeend",r),$.refresh()}function M(){u.innerHTML=""}function m(){g.classList.add("hidden")}function y(){g.classList.remove("hidden")}function A(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}function D(){const t=u.firstElementChild;if(!t)return;const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}const R=15;let l="",c=1,b=0;const I=document.querySelector(".form"),O=document.querySelector(".loadMore");d();I.addEventListener("submit",async t=>{if(t.preventDefault(),l=new FormData(t.target).get("search-text").trim(),c=1,!l){i.warning({message:"Please enter a search word!",position:"topRight"});return}M(),y();try{const a=await f(l,c),{hits:s,totalHits:e}=a;if(!s||s.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}h(s),b=Math.ceil(e/R),L()}catch(a){console.error(a),i.error({message:"Please try again later.",position:"topRight"})}finally{m(),t.target.reset()}});O.addEventListener("click",async()=>{c+=1,y();try{const t=await f(l,c),{hits:r}=t;if(!r||r.length===0){d();return}h(r),D(),L()}catch(t){console.error(t),i.error({message:"Please try again later.",position:"topRight"})}finally{m()}});function L(){c<b?A():(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}
//# sourceMappingURL=index.js.map
